name: 
on:
  push:
    branches:
      - main

jobs:
  cross-repo-pipeline:
    runs-on: ubuntu-latest
    steps: #here starts the action's setup
      - name: Build Central
        uses: amandastecz/pipeline-trigger@v1.1
        with:
          pat-token: ${{ secrets.PAT_TOKEN }}
          owner: ${{ vars.OWNER }}
          repo: ${{ vars.REPO }}
